### ISSUE TITLE
ReferenceError: docpad is not defined

### ISSUE THREAD

**Issue by marfalkov** [andruhon/docpad-plugin-tinylivereload#1]
docpad run

info: Welcome to DocPad v6.69.0
info: Plugins: eco, tinylivereload
info: Environment: development
info: DocPad listening to http://0.0.0.0:9778/ on directory /media/foo/docpad/out
error: Something went wrong with the action
error: An error occured: 
ReferenceError: docpad is not defined
  at TinyLiveReload.serverAfter (/media/foo/docpad/node_modules/docpad-plugin-tinylivereload/out/tinylivereload.plugin.js:33:9)
  at ambi (/media/foo/docpad/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:57:27)
  at Task.<anonymous> (/media/foo/docpad/node_modules/docpad/node_modules/event-emitter-grouped/out/lib/event-emitter-grouped.js:45:23)
  at ambi (/media/foo/docpad/node_modules/docpad/node_modules/ambi/out/lib/ambi.js:55:18)
  at fire (/media/foo/docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:373:25)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (/media/foo/docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:384:25)
  at Object._onImmediate (/media/foo/docpad/node_modules/docpad/node_modules/taskgroup/out/lib/taskgroup.js:400:26)
  at processImmediate [as _immediateCallback](timers.js:336:15)

**Comment by sklar** [comment]
@JesseBilsten +1
@andruhon Could you update version pls? Thanks.

**Comment by andruhon** [comment]
@JesseBilsten, @sklar 
I've updated the version. Could you please confirm if it works for you.

**Comment by sklar** [comment]
Thanks, but it still doesn't compute,]
I'm afraid that (to asure installing via `docpad install`) it's necessary to (re)publish it to npm.

**Comment by andruhon** [comment]
@sklar 
It should be fine now
npm now displaying a new version

**Comment by sklar** [comment]
@andruhon
Thanks a lot, but I give up..

I don't know why, but it's still not possible to install this plugin via `docpad install`.
Manual compilation is required (`cake compile`).

```
Error: Cannot find module '/Users/../Sites/test-docpad/node_modules/docpad-plugin-tinylivereload/out/tinylivereload.plugin.js'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at PluginLoader.load (/Users/../Sites/test-docpad/node_modules/docpad/out/lib/plugin-loader.js:131:28)
```

**Comment by andruhon** [comment]
@sklar 
Hi! I've reproduced the issue on my machine. Now it must be fixed. Could you please check again?

**Comment by sklar** [comment]
@andruhon sorry!
```
$ docpad install tinylivereload
info: Welcome to DocPad v6.70.1 (local installation: /Users/../Sites/test-docpad/node_modules/docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: eco, feedr, marked, menu, partials, related, sitemap
info: Environment: development
info: npm install docpad-plugin-tinylivereload@2 --save
npm WARN package.json test-docpad@0.1.0 No repository field.
docpad-plugin-tinylivereload@2.0.3 node_modules/docpad-plugin-tinylivereload
└── tiny-lr@0.1.5 (parseurl@1.3.0, qs@2.2.5, livereload-js@2.2.2, debug@2.0.0, faye-websocket@0.7.3, body-parser@1.8.4)
info: npm install
npm WARN package.json test-docpad@0.1.0 No repository field.
warning: Failed to load the plugin: docpad-plugin-tinylivereload at /Users/../Sites/test-docpad/node_modules/docpad-plugin-tinylivereload 
The error follows:
warning: An error occured: 
Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.
  at Object._base.(anonymous function) [as .coffee] (/Users/../Sites/test-docpad/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:210:17)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at PluginLoader.load (/Users/../Sites/test-docpad/node_modules/docpad/out/lib/plugin-loader.js:131:28)
  at /Users/../Sites/test-docpad/node_modules/docpad/out/lib/docpad.js:2563:27
  at PluginLoader.unsupported (/Users/../Sites/test-docpad/node_modules/docpad/out/lib/plugin-loader.js:106:7)
  at /Users/../Sites/test-docpad/node_modules/docpad/out/lib/docpad.js:2547:25
  at /Users/../Sites/test-docpad/node_modules/docpad/out/lib/plugin-loader.js:56:18
  at /Users/../Sites/test-docpad/node_modules/docpad/out/lib/plugin-loader.js:90:20
  at evalmachine.<anonymous>:271:14
  at /Users/../Sites/test-docpad/node_modules/docpad/node_modules/safefs/node_modules/graceful-fs/graceful-fs.js:102:5
  at Object.oncomplete (evalmachine.<anonymous>:107:15)
error: To report the above error, follow the guide at: http://docpad.org/bug-report
info: The action completed successfully
info: Shutting down... cya next time!
```

**Comment by andruhon** [comment]
Wow! Which version of the Node do you use?

**Comment by andruhon** [comment]
@sklar 
Wow! Which version of the Node do you use?

**Comment by sklar** [comment]
@andruhon node `v0.10.29`, what's yours pls?
It's not a big deal for me and it seems like it works fine for everyone else.]

**Comment by andruhon** [comment]
@sklar
My version is v0.12
It does work for me on windows. But I found that it is broken on ubuntu (With other output)

**Comment by andruhon** [comment]
@sklar My problem, it was a part of "node sudo" issue. So it works fine on ubuntu as well.

Could you please try it with node 0.12? I resolved the previous issue with setting the "main": "./src/tinylivereload.plugin.coffee" in package.json as recommended in the docpad documentation

**Comment by andruhon** [comment]
@sklar, i've created a new ticked for your issue, because it is acutally different from the subject of this ticket.
