### ISSUE TITLE
Docpad installation issue: coffee compilation

### ISSUE THREAD

**Issue by andruhon** [andruhon/docpad-plugin-tinylivereload#3]
Things like these happen under some circumstances:

```
Error: Cannot find module '/Users/../Sites/test-docpad/node_modules/docpad-plugin-tinylivereload/out/tinylivereload.plugin.js'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at PluginLoader.load (/Users/../Sites/test-docpad/node_modules/docpad/out/lib/plugin-loader.js:131:28)
```

and

```
$ docpad install tinylivereload
info: Welcome to DocPad v6.70.1 (local installation: /Users/../Sites/test-docpad/node_modules/docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: eco, feedr, marked, menu, partials, related, sitemap
info: Environment: development
info: npm install docpad-plugin-tinylivereload@2 --save
npm WARN package.json test-docpad@0.1.0 No repository field.
docpad-plugin-tinylivereload@2.0.3 node_modules/docpad-plugin-tinylivereload
└── tiny-lr@0.1.5 (parseurl@1.3.0, qs@2.2.5, livereload-js@2.2.2, debug@2.0.0, faye-websocket@0.7.3, body-parser@1.8.4)
info: npm install
npm WARN package.json test-docpad@0.1.0 No repository field.
warning: Failed to load the plugin: docpad-plugin-tinylivereload at /Users/../Sites/test-docpad/node_modules/docpad-plugin-tinylivereload 
The error follows:
warning: An error occured: 
Error: Use CoffeeScript.register() or require the coffee-script/register module to require .coffee.md files.
  at Object._base.(anonymous function) [as .coffee] (/Users/../Sites/test-docpad/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:210:17)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at PluginLoader.load (/Users/../Sites/test-docpad/node_modules/docpad/out/lib/plugin-loader.js:131:28)
  at /Users/../Sites/test-docpad/node_modules/docpad/out/lib/docpad.js:2563:27
  at PluginLoader.unsupported (/Users/../Sites/test-docpad/node_modules/docpad/out/lib/plugin-loader.js:106:7)
  at /Users/../Sites/test-docpad/node_modules/docpad/out/lib/docpad.js:2547:25
  at /Users/../Sites/test-docpad/node_modules/docpad/out/lib/plugin-loader.js:56:18
  at /Users/../Sites/test-docpad/node_modules/docpad/out/lib/plugin-loader.js:90:20
  at evalmachine.<anonymous>:271:14
  at /Users/../Sites/test-docpad/node_modules/docpad/node_modules/safefs/node_modules/graceful-fs/graceful-fs.js:102:5
  at Object.oncomplete (evalmachine.<anonymous>:107:15)
error: To report the above error, follow the guide at: http://docpad.org/bug-report
info: The action completed successfully
info: Shutting down... cya next time!
```

reported by @sklar in #1

**Comment by andruhon** [comment]
Ok, @sklar, It is a final attempt. I've got rid of coffee files, so there's nothing to compile. It will presumably work on any 0.10+ node

**Comment by sklar** [comment]
Sorry to see that you dropped coffeescript files, but I confirm that there's no installation problems on `v0.10.6` (OSX 10.8.5) anymore.
Thanks!

**Comment by andruhon** [comment]
@sklar 
No worries, I'm not a fan of coffeescript. Just tried to follow guidelines initially, but all this coffeescript seems to cause cross-version issues sometimes.
